name = "vpn-manager"
main = "index.js"
compatibility_date = "2025-09-22"

account_id = "877922defd6351a3856f3b342cce03e3" # User should replace this

# KV Namespace binding.
# IMPORTANT: You must create a KV Namespace in your Cloudflare dashboard
# and name it "PROXY_STATUS". Then, come back to this file and paste its ID here.
kv_namespaces = [
  { binding = "PROXY_STATUS", id = "a99a22a9fe894c7d8befab28d890d27b" }
]

[site]
bucket = "./"
